package core

type MetricsSnapshot struct {
	TotalRequests                     int64 `json:"total_requests"`
	TotalLlmCalls                     int64 `json:"total_llm_calls"`
	TotalInputTokens                  int64 `json:"total_input_tokens"`
	TotalOutputTokens                 int64 `json:"total_output_tokens"`
	TotalToolCalls                    int64 `json:"total_tool_calls"`
	TotalToolFailures                 int64 `json:"total_tool_failures"`
	TotalToolTimeouts                 int64 `json:"total_tool_timeouts"`
	TotalLlmRetries                   int64 `json:"total_llm_retries"`
	TotalLlmErrors                    int64 `json:"total_llm_errors"`
	ApprovalDecisionsRecorded         int64 `json:"approval_decisions_recorded"`
	ApprovalDecisionsRejected         int64 `json:"approval_decisions_rejected"`
	SessionEvictions                  int64 `json:"session_evictions"`
	SessionCapacityRejects            int64 `json:"session_capacity_rejects"`
	EstimatedTokenAdmissionRejects    int64 `json:"estimated_token_admission_rejects"`
	BrowserCancellationResets         int64 `json:"browser_cancellation_resets"`
	PluginBridgeAuthFailures          int64 `json:"plugin_bridge_auth_failures"`
	PluginBridgeRestartAttempts       int64 `json:"plugin_bridge_restart_attempts"`
	PluginBridgeRestartFailures       int64 `json:"plugin_bridge_restart_failures"`
	ProcessStarts                     int64 `json:"process_starts"`
	ProcessCompletions                int64 `json:"process_completions"`
	ProcessFailures                   int64 `json:"process_failures"`
	ProcessKills                      int64 `json:"process_kills"`
	ProcessTimeouts                   int64 `json:"process_timeouts"`
	ProcessHistoryEvictions           int64 `json:"process_history_evictions"`
	SandboxLeaseCreates               int64 `json:"sandbox_lease_creates"`
	SandboxLeaseReuses                int64 `json:"sandbox_lease_reuses"`
	SandboxLeaseRecoveries            int64 `json:"sandbox_lease_recoveries"`
	RetentionSweepRuns                int64 `json:"retention_sweep_runs"`
	RetentionSweepFailures            int64 `json:"retention_sweep_failures"`
	RetentionArchivedItems            int64 `json:"retention_archived_items"`
	RetentionDeletedItems             int64 `json:"retention_deleted_items"`
	RetentionSkippedProtectedSessions int64 `json:"retention_skipped_protected_sessions"`
	OperatorAuditWriteFailures        int64 `json:"operator_audit_write_failures"`
	RuntimeEventWriteFailures         int64 `json:"runtime_event_write_failures"`
	SessionCacheHits                  int64 `json:"session_cache_hits"`
	SessionCacheMisses                int64 `json:"session_cache_misses"`
	MemoryRecallSearches              int64 `json:"memory_recall_searches"`
	MemoryRecallHits                  int64 `json:"memory_recall_hits"`
	MemoryCompactions                 int64 `json:"memory_compactions"`
	PromptCacheReads                  int64 `json:"prompt_cache_reads"`
	PromptCacheWrites                 int64 `json:"prompt_cache_writes"`
	PromptCacheWarmRuns               int64 `json:"prompt_cache_warm_runs"`
	PromptCacheWarmSkips              int64 `json:"prompt_cache_warm_skips"`
	PromptCacheWarmFailures           int64 `json:"prompt_cache_warm_failures"`
	PulseRuns                         int64 `json:"pulse_runs"`
	PulseSkips                        int64 `json:"pulse_skips"`
	PulseAlerts                       int64 `json:"pulse_alerts"`
	PulseOkSuppressed                 int64 `json:"pulse_ok_suppressed"`
	PulseErrors                       int64 `json:"pulse_errors"`
	RetentionLastRunAtUnixSeconds     int64 `json:"retention_last_run_at_unix_seconds"`
	RetentionLastRunDurationMs        int64 `json:"retention_last_run_duration_ms"`
	RetentionLastRunSucceeded         int32 `json:"retention_last_run_succeeded"`
	PulseLastRunDurationMs            int64 `json:"pulse_last_run_duration_ms"`
	ActiveSessions                    int32 `json:"active_sessions"`
	CircuitBreakerState               int32 `json:"circuit_breaker_state"`
	RetainedProcesses                 int32 `json:"retained_processes"`
}
