package graphify

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

var _ IGraphExporter = (*ObsidianExporter)(nil)

type ObsidianExporter struct {
}

// Export implements [IGraphExporter].
func (e *ObsidianExporter) Export(ctx context.Context, graph KnowledgeGraph, outputPath string) error {
	if strings.TrimSpace(outputPath) == "" {
		return fmt.Errorf("outputPath cannot be empty")
	}

	if err := os.MkdirAll(outputPath, 0755); err != nil {
		return err
	}

	nodes := graph.GetNodes()

	communities := make(map[int]string)
	for _, n := range nodes {
		if n.Community != -1 {
			communities[n.Community] = fmt.Sprintf("Community %d", n.Community)
		}
	}

	for _, node := range nodes {
		content := e.generateNodeFile(graph, node, communities)
		filename := e.safeFilename(node.LabelOrID()) + ".md"
		filePath := filepath.Join(outputPath, filename)
		if err := os.WriteFile(filePath, []byte(content), 0644); err != nil {
			return err
		}
	}

	indexContent := e.generateIndexFile(graph, nodes, communities)
	if err := os.WriteFile(filepath.Join(outputPath, "_Index.md"), []byte(indexContent), 0644); err != nil {
		return err
	}

	return nil
}

func (e *ObsidianExporter) generateNodeFile(g KnowledgeGraph, node GraphNode, communities map[int]string) string {
	var sb strings.Builder
	nodeLabel := node.LabelOrID()

	// YAML frontmatter
	sb.WriteString("---\n")
	sb.WriteString(fmt.Sprintf("id: %s\n", node.Id))
	sb.WriteString(fmt.Sprintf("type: %s\n", node.Type))

	if node.Community != -1 {
		if comm, ok := communities[node.Community]; ok {
			sb.WriteString(fmt.Sprintf("community: \"%s\"\n", comm))
		}
	}

	if node.Metadata != nil {
		keys := make([]string, 0, len(node.Metadata))
		for k := range node.Metadata {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			v := node.Metadata[k]
			if k != "label" && strings.TrimSpace(v) != "" {
				sb.WriteString(fmt.Sprintf("%s: \"%s\"\n", k, e.escapeYaml(v)))
			}
		}
	}

	degree := g.GetDegree(node.Id)
	sb.WriteString(fmt.Sprintf("connections: %d\n", degree))
	sb.WriteString("---\n\n")

	// Main content
	sb.WriteString(fmt.Sprintf("# %s\n\n", nodeLabel))

	// Metadata section
	sb.WriteString("## Properties\n\n")
	sb.WriteString(fmt.Sprintf("- **Type:** %s\n", node.Type))
	sb.WriteString(fmt.Sprintf("- **ID:** `%s`\n", node.Id))
	sb.WriteString(fmt.Sprintf("- **Connections:** %d\n", degree))
	if node.Community != -1 {
		if comm, ok := communities[node.Community]; ok {
			sb.WriteString(fmt.Sprintf("- **Community:** %s\n", comm))
		}
	}
	if src, ok := node.Metadata["source_file"]; ok {
		sb.WriteString(fmt.Sprintf("- **Source:** `%s`\n", src))
	}
	sb.WriteString("\n")

	// Connections grouped by relationship
	connections := e.getConnectionsByRelationship(g, node)
	if len(connections) > 0 {
		sb.WriteString("## Connections\n\n")
		keys := make([]string, 0, len(connections))
		for k := range connections {
			keys = append(keys, k)
		}
		sort.Slice(keys, func(i, j int) bool {
			return len(connections[keys[i]]) > len(connections[keys[j]])
		})
		for _, rel := range keys {
			sb.WriteString(fmt.Sprintf("### %s\n\n", rel))
			nodes := connections[rel]
			sort.Slice(nodes, func(i, j int) bool {
				return nodes[i].LinkedNode.LabelOrID() < nodes[j].LinkedNode.LabelOrID()
			})
			for _, n := range nodes {
				confTag := ""
				if n.Confidence != ConfidenceExtracted {
					confTag = fmt.Sprintf(" `%s`", n.Confidence)
				}
				sb.WriteString(fmt.Sprintf("- [[%s]]%s\n", n.LinkedNode.LabelOrID(), confTag))
			}
			sb.WriteString("\n")
		}
	} else {
		sb.WriteString("## Connections\n\n*No connections found*\n\n")
	}

	sb.WriteString("---\n\n*Generated by graphify. Part of the knowledge graph vault.*\n")

	return sb.String()
}

func (e *ObsidianExporter) generateIndexFile(g KnowledgeGraph, nodes []GraphNode, communities map[int]string) string {
	var sb strings.Builder

	sb.WriteString("---\n")
	sb.WriteString("title: Knowledge Graph Index\n")
	sb.WriteString(fmt.Sprintf("generated: %s\n", time.Now().Format("2006-01-02 15:04:05")))
	sb.WriteString("---\n\n")

	sb.WriteString("# Knowledge Graph Index\n\n")
	sb.WriteString("> Central hub for navigating the knowledge graph in Obsidian\n\n")

	sb.WriteString("## Statistics\n\n")
	sb.WriteString(fmt.Sprintf("- **Nodes:** %d\n", len(nodes)))
	sb.WriteString(fmt.Sprintf("- **Edges:** %d\n", g.EdgeCount()))
	sb.WriteString(fmt.Sprintf("- **Communities:** %d\n\n", len(communities)))

	// Top nodes by degree
	topNodes := g.GetHighestDegreeNodes(20)
	if len(topNodes) > 0 {
		sb.WriteString("## Most Connected Nodes\n\n")
		for _, nd := range topNodes {
			sb.WriteString(fmt.Sprintf("- [[%s]] (%d connections)\n", nd.Node.LabelOrID(), nd.Degree))
		}
		sb.WriteString("\n")
	}

	// Nodes by community
	if len(communities) > 0 {
		sb.WriteString("## By Community\n\n")
		commGroups := make(map[int][]GraphNode)
		for _, n := range nodes {
			if n.Community != -1 {
				commGroups[n.Community] = append(commGroups[n.Community], n)
			}
		}
		// 按社区节点数降序
		keys := make([]int, 0, len(commGroups))
		for k := range commGroups {
			keys = append(keys, k)
		}
		sort.Slice(keys, func(i, j int) bool {
			return len(commGroups[keys[i]]) > len(commGroups[keys[j]])
		})
		for _, k := range keys {
			sb.WriteString(fmt.Sprintf("### %s\n\n", communities[k]))
			sb.WriteString(fmt.Sprintf("*%d nodes*\n\n", len(commGroups[k])))
			sort.Slice(commGroups[k], func(i, j int) bool {
				return g.GetDegree(commGroups[k][i].Id) > g.GetDegree(commGroups[k][j].Id)
			})
			for i, n := range commGroups[k] {
				if i >= 10 {
					sb.WriteString(fmt.Sprintf("- *... and %d more*\n", len(commGroups[k])-10))
					break
				}
				sb.WriteString(fmt.Sprintf("- [[%s]]\n", n.LabelOrID()))
			}
			sb.WriteString("\n")
		}
	}

	// Node types
	typeGroups := make(map[string][]GraphNode)
	for _, n := range nodes {
		typeGroups[n.Type] = append(typeGroups[n.Type], n)
	}
	typeKeys := make([]string, 0, len(typeGroups))
	for k := range typeGroups {
		typeKeys = append(typeKeys, k)
	}
	sort.Slice(typeKeys, func(i, j int) bool {
		return len(typeGroups[typeKeys[i]]) > len(typeGroups[typeKeys[j]])
	})
	if len(typeKeys) > 0 {
		sb.WriteString("## By Type\n\n")
		for _, t := range typeKeys {
			sb.WriteString(fmt.Sprintf("### %s\n", t))
			sb.WriteString(fmt.Sprintf("*%d nodes*\n\n", len(typeGroups[t])))
		}
	}

	sb.WriteString("---\n\n*Generated by [graphify](https://github.com/safishamsi/graphify)*\n")
	return sb.String()
}

func (e *ObsidianExporter) getConnectionsByRelationship(g KnowledgeGraph, node GraphNode) map[string][]ConnectionEntry {
	result := make(map[string][]ConnectionEntry)

	edges := g.GetEdgesById(node.Id)
	for _, edge := range edges {
		relationship := edge.Relationship
		if relationship == "" {
			relationship = "related_to"
		}

		var linkedNode GraphNode
		if edge.Source.Id == node.Id {
			linkedNode = edge.Target
		} else {
			linkedNode = edge.Source
		}

		list := result[relationship]
		found := false
		for _, item := range list {
			if item.LinkedNode.Id == linkedNode.Id {
				found = true
				break
			}
		}
		if !found {
			result[relationship] = append(result[relationship], ConnectionEntry{
				LinkedNode: linkedNode,
				Confidence: edge.Confidence,
			})
		}
	}

	return result
}

func (e *ObsidianExporter) safeFilename(name string) string {
	safe := name
	for _, c := range filepath.Base(name) {
		if strings.ContainsRune(`\/:*?"<>|`, c) || c == 0 {
			safe = strings.ReplaceAll(safe, string(c), "_")
		}
	}
	if len(safe) > 100 {
		safe = safe[:100]
	}
	return safe
}

func (e *ObsidianExporter) escapeYaml(value string) string {
	if value == "" {
		return value
	}
	s := value
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	s = strings.ReplaceAll(s, "\n", `\n`)
	s = strings.ReplaceAll(s, "\r", "")
	return s
}

// GetFormat implements [IGraphExporter].
func (o *ObsidianExporter) GetFormat() string {
	return "obsidian"
}
